### ISSUE TITLE
Use java.io.tmpdir or any other suitable folder as a temporary folder

### ISSUE THREAD

**Issue by chahuistle** [qbicsoftware-archive/nexus-listener-service#3]
This is to avoid a "permission denied" error when downloading an artifact.

**Comment by chahuistle** [comment]
This is the associated exception:

```
[ERROR] [Client] - ERROR WHILE DOWNLOADING FILE: IOException 
java.io.FileNotFoundException: sample-portlet-1.0.0-20181018.083541-29208644702450724874.war (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_181]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_181]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_181]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101) ~[?:1.8.0_181]
	at life.qbic.service.Client.downloadFromURL(Client.java:42) [nexus-listener-service-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at life.qbic.service.NexusListenerService.processPOST(NexusListenerService.java:129) [nexus-listener-service-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at life.qbic.service.NexusListenerService$1.serve(NexusListenerService.java:76) [nexus-listener-service-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945) [nexus-listener-service-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192) [nexus-listener-service-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```
